In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import pickle

In [2]:
df=pd.read_csv('test_Loan_Pred.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

In [4]:
df.nunique()

Loan_ID              367
Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      314
CoapplicantIncome    194
LoanAmount           144
Loan_Amount_Term      12
Credit_History         2
Property_Area          3
dtype: int64

### Handling null values

In [5]:
df.isna().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [6]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
dtype: object

In [7]:
cat_col=['Gender','Dependents','Self_Employed']
for col in cat_col:
    mode=df[col].mode().values[0]
    df[col]=df[col].fillna(mode)

In [8]:
num_col=['LoanAmount','Loan_Amount_Term','Credit_History']
for col in num_col:
    median=df[col].median()
    df[col]=df[col].fillna(median)

In [9]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

### Converting Categorical to numeric

In [10]:
mapping_df=pd.read_csv('mapping_dict_train.csv')
mapping_df

              id  values
0         Female       0
1           Male       1
2             No       0
3            Yes       1
4              0       0
5              1       1
6              2       2
7             3+       3
8       Graduate       0
9   Not Graduate       1
10         Rural       0
11     Semiurban       1
12         Urban       2
13             N       0
14             Y       1

In [11]:
mapping_dict=dict(mapping_df.values)
mapping_dict

{'Female': 0,
 'Male': 1,
 'No': 0,
 'Yes': 1,
 '0': 0,
 '1': 1,
 '2': 2,
 '3+': 3,
 'Graduate': 0,
 'Not Graduate': 1,
 'Rural': 0,
 'Semiurban': 1,
 'Urban': 2,
 'N': 0,
 'Y': 1}

In [12]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
dtype: object

In [13]:
cat_col = ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area']

for col in cat_col:
   df[col] = df[col].apply(lambda x: mapping_dict[x])

In [14]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1,1,0,0,0,5720,0,110.0,360.0,1.0,2
1,LP001022,1,1,1,0,0,3076,1500,126.0,360.0,1.0,2
2,LP001031,1,1,2,0,0,5000,1800,208.0,360.0,1.0,2
3,LP001035,1,1,2,0,0,2340,2546,100.0,360.0,1.0,2
4,LP001051,1,0,0,1,0,3276,0,78.0,360.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,1,1,3,1,1,4009,1777,113.0,360.0,1.0,2
363,LP002975,1,1,0,0,0,4158,709,115.0,360.0,1.0,2
364,LP002980,1,0,0,0,0,3250,1993,126.0,360.0,1.0,1
365,LP002986,1,1,0,0,0,5000,2393,158.0,360.0,1.0,0
366,LP002989,1,0,0,0,1,9200,0,98.0,180.0,1.0,0

In [15]:
final_df=pd.DataFrame(df['Loan_ID'])
final_df.head()

    Loan_ID
0  LP001015
1  LP001022
2  LP001031
3  LP001035
4  LP001051

In [16]:
df=df.iloc[:,1:]
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,1,0,0,0,5720,0,110.0,360.0,1.0,2
1,1,1,1,0,0,3076,1500,126.0,360.0,1.0,2
2,1,1,2,0,0,5000,1800,208.0,360.0,1.0,2
3,1,1,2,0,0,2340,2546,100.0,360.0,1.0,2
4,1,0,0,1,0,3276,0,78.0,360.0,1.0,2

### Standardization

In [17]:
with open('Standard_scaler_train.pkl','rb') as file:
    ss=pickle.load(file)

In [18]:
ss

StandardScaler()

In [19]:
x_ft=ss.transform(df)     # yahan ss.fit_transform use nahi kiya kyonki fit actual values ka mean or std calculation me use krta hai jabki hum train file ka mean or std use krr rhe hain 
x_ft=pd.DataFrame(x_ft,columns = df.columns)
x_ft.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.47918,0.740708,-0.718898,-0.549793,-0.382099,0.293527,-0.630154,-0.398893,0.271476,0.414462,1.224522
1,0.47918,0.740708,0.300727,-0.549793,-0.382099,-0.431719,0.009064,-0.053595,0.271476,0.414462,1.224522
2,0.47918,0.740708,1.320352,-0.549793,-0.382099,0.096032,0.136908,1.716057,0.271476,0.414462,1.224522
3,0.47918,0.740708,1.320352,-0.549793,-0.382099,-0.633602,0.454813,-0.614704,0.271476,0.414462,1.224522
4,0.47918,-1.350059,-0.718898,1.818865,-0.382099,-0.376859,-0.630154,-1.089489,0.271476,0.414462,1.224522

### Predicting the Final data

In [45]:
with open('best_model.pkl','rb') as file :
    lr=pickle.load(file)

In [46]:
lr

LogisticRegression()

In [47]:
pred=lr.predict(x_ft)
pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [48]:
pred_df=pd.DataFrame(pred,columns=['Loan_Status'])
pred_df.head()

   Loan_Status
0            1
1            1
2            1
3            1
4            1

In [49]:
map_dict={0:'N', 1:'Y'}
pred_df['Loan_Status']=pred_df['Loan_Status'].apply(lambda x: map_dict[x])
#pred_df['Loan_Status'] = pred_df['Loan_Status'].astype(int).map(map_dict)
pred_df.head()

  Loan_Status
0           Y
1           Y
2           Y
3           Y
4           Y

In [50]:
final_df.head()

    Loan_ID
0  LP001015
1  LP001022
2  LP001031
3  LP001035
4  LP001051

In [51]:
final_df.shape, pred_df.shape

((367, 1), (367, 1))

In [52]:
submission_file=pd.concat([final_df,pred_df],axis=1)
submission_file.head()

    Loan_ID Loan_Status
0  LP001015           Y
1  LP001022           Y
2  LP001031           Y
3  LP001035           Y
4  LP001051           Y

In [53]:
submission_file.to_csv('Final_Submission.csv',index=False)
submission_file

      Loan_ID Loan_Status
0    LP001015           Y
1    LP001022           Y
2    LP001031           Y
3    LP001035           Y
4    LP001051           Y
..        ...         ...
362  LP002971           Y
363  LP002975           Y
364  LP002980           Y
365  LP002986           Y
366  LP002989           Y

[367 rows x 2 columns]

In [54]:
submission_file['Loan_Status'].value_counts()

Loan_Status
Y    308
N     59
Name: count, dtype: int64